/*
Copyright (C) 1994-1995 Apogee Software, Ltd.
Copyright (C) 2002-2015 icculus.org, GNU/Linux port
Copyright (C) 2017-2018 Steven LeVesque
Copyright (C) 2025 lunarmeadow (she/her)
Copyright (C) 2025 erysdren (it/its)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef _KPFDATA_H
#define _KPFDATA_H

#include "miniz.h"
#include "miniz_zip.h"
#include "rt_def.h"

#ifndef ARRAY_COUNT
#define ARRAY_COUNT(a) (sizeof(a)/sizeof(*a))
#endif

// enum PatchType {
//     PATCH,

// };

// enum ScaleType {
//     SHAPE,
    
// };

// // Used for decoding patch parameters from .json file.
// typedef struct
// {
// 	short origsize; // the orig size of "grabbed" gfx
// 	short width;	// bounding box size
// 	short height;
// 	short leftoffset; // pixels to the left of origin
// 	short topoffset;  // pixels above the origin
// } decode_patch_t;

// typedef struct
// {
// 	short origsize; // the orig size of "grabbed" gfx
// 	short width;	// bounding box size
// 	short height;
// 	short leftoffset; // pixels to the left of origin
// 	short topoffset;  // pixels above the origin
// 	short translevel;
// } decode_transpatch_t;


// generated by ZipChar
static const char *betaWalls[] = {
    "WALB03",
    "WALB04",
    "WALB05",
    "WALB06",
    "WALB07",
    "WALB08",
    "WALB13",
    "WALB14",
    "WALB15",
    "WALB16",
    "WALB17",
    "WALB18",
    "WALB19",
    "WALB20",
    "WALB21",
    "WALB26",
    "WALB27",
    "WALB28",
    "WALB40",
    "WALB41",
    "WALB42",
    "WALB44",
    "WALB46",
    "WALB48",
    "WALB51",
    "WALB58",
    "WALB59",
    "WALB60",
    "WALB61",
    "WALB69",
    "WALB70",
    "WALB71"
};

static const char *altSounds[] = {
    "P_A2PIST_vb",
    "P_AMP40_vb",
    "P_APISTL_vb",
    "P_BATBLA_vb",
    "P_BATHIT_vb",
    "P_BAZOOK_vb",
    "P_DRUNK_vb",
    "P_FIREBM_vb",
    "P_FWFIRE_vb",
    "P_GRAVFI_vb",
    "P_HEATSK_vb",
    "P_SPLITS_vb"
};

// each index corresponds 1:1 with altSounds table.
// i do not feel like implementing a proper dictionary for this, so, oh well, it sucks...
static int altSoundMapping[] = {
    49, // SD_ATKTWOPISTOLSND
    50, // SD_ATKMP40SND
    48, // SD_ATKPISTOLSND
    73, // SD_EXCALIBLASTSND
    71, // SD_EXCALIHITSND
    54, // SD_BAZOOKAFIRESND
    57, // SD_DRUNKFIRESND
    55, // SD_FIREBOMBFIRESND
    58, // SD_FLAMEWALLFIRESND
    63, // SD_GRAVFIRESND
    56, // SD_HEATSEEKFIRESND
    60 // SD_SPLITFIRESND
};

// alas, shitty as ever
// this remaps beta walls to hand-selected approximations from the base game,
// to allow RTLX maps to be played for people who don't yet own LE,
// but would like to play community maps made with the LE level editor
static int bwallFallback[] = {
    11,
    12,
    13,
    14,
    15,
    16,
    20,
    21,
    22,
    23,
    24,
    29,
    30,
    31,
    32,
    31,
    36,
    37,
    29,
    5,
    41,
    59,
    59,
    63,
    49,
    54,
    54,
    54,
    54,
    61,
    61,
    89
};

static const char *bigJojHaha[] = {
    "BIGJDEAD",
    "BIGJDIE1",
    "BIGJDIE2",
    "BIGJDIE3",
    "BIGJDIE4",
    "BIGJPAIN1",
    "BIGJPAIN2",
    "BIGJS1",
    "BIGJS2",
    "BIGJS3",
    "BIGJS4",
    "BIGJS5",
    "BIGJS6",
    "BIGJS7",
    "BIGJS8",
    "BIGJSHOO1",
    "BIGJSHOO2",
    "BIGJSHOO3",
    "BIGJSHOO4",
    "BIGJTOSS1",
    "BIGJTOSS2",
    "BIGJTOSS3",
    "BIGJTOSS4",
    "BIGJTOSS5",
    "BIGJTOSS6",
    "BIGJTOSS7",
    "BIGJTOSS8",
    "BIGJW11",
    "BIGJW12",
    "BIGJW13",
    "BIGJW14",
    "BIGJW15",
    "BIGJW16",
    "BIGJW17",
    "BIGJW18",
    "BIGJW21",
    "BIGJW22",
    "BIGJW23",
    "BIGJW24",
    "BIGJW25",
    "BIGJW26",
    "BIGJW27",
    "BIGJW28",
    "BIGJW31",
    "BIGJW32",
    "BIGJW33",
    "BIGJW34",
    "BIGJW35",
    "BIGJW36",
    "BIGJW37",
    "BIGJW38",
    "BIGJW41",
    "BIGJW42",
    "BIGJW43",
    "BIGJW44",
    "BIGJW45",
    "BIGJW46",
    "BIGJW47",
    "BIGJW48"
};

#endif
