/*
Copyright (C) 1994-1995 Apogee Software, Ltd.
Copyright (C) 2002-2015 icculus.org, GNU/Linux port
Copyright (C) 2017-2018 Steven LeVesque
Copyright (C) 2025 lunarmeadow (she/her)
Copyright (C) 2025 erysdren (it/its)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef _KPFDATA_H
#define _KPFDATA_H

#include "miniz.h"
#include "miniz_zip.h"
#include "rt_def.h"

#ifndef ARRAY_COUNT
#define ARRAY_COUNT(a) (sizeof(a)/sizeof(*a))
#endif

enum PatchType {
    PATCH,

};

enum ScaleType {
    SHAPE,
    
};

// Used for decoding patch parameters from .json file.
typedef struct
{
	short origsize; // the orig size of "grabbed" gfx
	short width;	// bounding box size
	short height;
	short leftoffset; // pixels to the left of origin
	short topoffset;  // pixels above the origin
} decode_patch_t;

typedef struct
{
	short origsize; // the orig size of "grabbed" gfx
	short width;	// bounding box size
	short height;
	short leftoffset; // pixels to the left of origin
	short topoffset;  // pixels above the origin
	short translevel;
} decode_transpatch_t;


// generated by ZipChar
static const char *betaWalls[] = {
    "WALB03",
    "WALB04",
    "WALB05",
    "WALB06",
    "WALB07",
    "WALB08",
    "WALB13",
    "WALB14",
    "WALB15",
    "WALB16",
    "WALB17",
    "WALB18",
    "WALB19",
    "WALB20",
    "WALB21",
    "WALB26",
    "WALB27",
    "WALB28",
    "WALB40",
    "WALB41",
    "WALB42",
    "WALB44",
    "WALB46",
    "WALB48",
    "WALB51",
    "WALB58",
    "WALB59",
    "WALB60",
    "WALB61",
    "WALB69",
    "WALB70",
    "WALB71"
};

static const char *floors[] = {
    "FLOOR1",
    "FLOOR10",
    "FLOOR11",
    "FLOOR12",
    "FLOOR14",
    "FLOOR17",
    "FLOOR4",
    "FLOOR5",
    "FLOOR6"
};

static const char *ceils[] = {
    "CEIL12",
    "CEIL13",
    "CEIL17",
    "CEIL2",
    "CEIL5",
    "CEIL6"
};

static const char *bigJojHaha[] = {
    "BIGJDEAD",
    "BIGJDIE1",
    "BIGJDIE2",
    "BIGJDIE3",
    "BIGJDIE4",
    "BIGJPAIN1",
    "BIGJPAIN2",
    "BIGJS1",
    "BIGJS2",
    "BIGJS3",
    "BIGJS4",
    "BIGJS5",
    "BIGJS6",
    "BIGJS7",
    "BIGJS8",
    "BIGJSHOO1",
    "BIGJSHOO2",
    "BIGJSHOO3",
    "BIGJSHOO4",
    "BIGJTOSS1",
    "BIGJTOSS2",
    "BIGJTOSS3",
    "BIGJTOSS4",
    "BIGJTOSS5",
    "BIGJTOSS6",
    "BIGJTOSS7",
    "BIGJTOSS8",
    "BIGJW11",
    "BIGJW12",
    "BIGJW13",
    "BIGJW14",
    "BIGJW15",
    "BIGJW16",
    "BIGJW17",
    "BIGJW18",
    "BIGJW21",
    "BIGJW22",
    "BIGJW23",
    "BIGJW24",
    "BIGJW25",
    "BIGJW26",
    "BIGJW27",
    "BIGJW28",
    "BIGJW31",
    "BIGJW32",
    "BIGJW33",
    "BIGJW34",
    "BIGJW35",
    "BIGJW36",
    "BIGJW37",
    "BIGJW38",
    "BIGJW41",
    "BIGJW42",
    "BIGJW43",
    "BIGJW44",
    "BIGJW45",
    "BIGJW46",
    "BIGJW47",
    "BIGJW48"
};

#endif